In [116]:
# Tic-Tac-Toe Program using Monte Carlo in Python
  
# importing libraries
import numpy as np
import random
from time import sleep
  
# Creates an empty board
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
  
# Check for empty places on board
def empty_space(board):
    l = []
      
    for i in range(len(board)):
        for j in range(len(board)):
              
            if board[i][j] == 0:
                l.append((i, j))
    return(l)

# chooses the best play after reading into the next turn
def mc_choice(board, player):
    selection = empty_space(board)
    score = []

    for i in selection:
      copy_board = board.copy()
      current_loc = i
      copy_board[current_loc] = player
      result = evaluate(copy_board)

      # if it is possible to win then play it immediately
      if result == 2:
        return(copy_board)

      selection_2 = empty_space(copy_board)
      points = 0

      for j in selection_2:
        copy_copy_board = copy_board.copy()
        copy_copy_board[j] = 1
        outcome = evaluate(copy_copy_board)

        if outcome == 1: # if losing
          points = points - 1
        elif outcome == -1: # if draw
          points = points + 1

      score_child = points / len(selection_2)
      score.append(score_child)

    best_score = max(score)
    best_loc = list_index_all(score, best_score)

    bestest_loc = selection[random.choice(best_loc)]
    board[bestest_loc] = player

    return(board)

# for finding index of all elements in a list with the same value
def list_index_all(l, value):

    l1 = []
    for i in range(len(l)):
      if l[i] == value:
        l1.append(i)
    
    return l1
    
# chooses the next move randomly with weighted probability    
def mc_weighted_choice(board, player):
    selection = empty_space(board)
    score = []

    for i in selection:
      copy_board = board.copy()
      current_loc = i
      copy_board[current_loc] = player
      result = evaluate(copy_board)

      if result == 2:
        return(copy_board)

      selection_2 = empty_space(copy_board)
      points = 100 # for ease of assigning weights

      for j in selection_2:
        copy_copy_board = copy_board.copy()
        copy_copy_board[j] = 1
        outcome = evaluate(copy_copy_board)

        if outcome == 1:
          points = points - 49 # no particular reason in keeping 49
        elif outcome == -1:
          points = points + 40
          
      score_child = points / len(selection_2)
      score.append(score_child)

    best_loc = random.choices(selection, weights=score, k=10)
    board[best_loc[0]] = player
    return(board)


# Checks horizontally for victory 
def row_win(board, player):
    for x in range(len(board)):
        win = True
          
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
                  
        if win == True:
            return(win)
    return(win)
  
# Checks vertically for victory
def col_win(board, player):
    for x in range(len(board)):
        win = True
          
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
                  
        if win == True:
            return(win)
    return(win)
  
# Checks diagonally for victory
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
  
# Checks for match status
def evaluate(board):
    winner = 0
      
    for player in [1, 2]:
        if (row_win(board, player) or
            col_win(board,player) or 
            diag_win(board,player)):
                 
            winner = player
              
    # In case of draw
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

# Player's input is registered in the board
def player_choice(board, player, inp):
    inp = inp - 1
    x = int(inp / 3)
    y = int(inp % 3)
    if board[x][y] != 0:
      return board, 0 
    board[x][y] = player
    return board, 1

# For printing the 3x3 board
def print_board(board):
    for i in range(3):
        print(board[i])

# Main function to start the game
def play_game():
    board = create_board()
    winner = 0
    counter = 1
    print_board(board)
    sleep(1)
    valid = 1
      
    while winner == 0:
        for player in [1, 2]:
          if player == 1: # Human
            print("Choose a spot to play (1-9):")
            while True:
              inp = int(input())
              board, valid = player_choice(board, player, inp)
              if valid == 1:
                break
              print("Choose an empty spot")

          if player == 2: # Computer

            # For weighted probabilities among all options
            # board = mc_weighted_choice(board, player) 

            # For deterministically choosing best option
            board = mc_choice(board, player)

          print("Board after " + str(counter) + " move(s)")
          print_board(board)
          sleep(1)
          counter += 1
          winner = evaluate(board)
          if winner != 0:
              break

    if winner == 1:
      print("You have won!")
    if winner == 2:
      print("You lost! Too bad.")
    if winner == -1:
      print("The match has drawn.")
    return
  
# Driver Code
play_game()

[0 0 0]
[0 0 0]
[0 0 0]
Choose a spot to play (1-9):
9
Board after 1 move(s)
[0 0 0]
[0 0 0]
[0 0 1]
Board after 2 move(s)
[0 0 0]
[0 0 2]
[0 0 1]
Choose a spot to play (1-9):
5
Board after 3 move(s)
[0 0 0]
[0 1 2]
[0 0 1]
Board after 4 move(s)
[2 0 0]
[0 1 2]
[0 0 1]
Choose a spot to play (1-9):
8
Board after 5 move(s)
[2 0 0]
[0 1 2]
[0 1 1]
Board after 6 move(s)
[2 0 0]
[0 1 2]
[2 1 1]
Choose a spot to play (1-9):
4
Board after 7 move(s)
[2 0 0]
[1 1 2]
[2 1 1]
Board after 8 move(s)
[2 2 0]
[1 1 2]
[2 1 1]
Choose a spot to play (1-9):
3
Board after 9 move(s)
[2 2 1]
[1 1 2]
[2 1 1]
The match has drawn.
